<?php
error_reporting (E_ALL); ini_set('display_errors', 1);

require_once __DIR__ . '/libs/autoload.php';

$ctrl = (isset($_GET['ctrl']) AND !empty($_GET['ctrl'])) ? $_GET['ctrl'] : 'News';
$act = (isset($_GET['act']) AND !empty($_GET['act'])) ? $_GET['act'] : 'All';

$controllerClassName = $ctrl . 'Controller';
$method = 'action' . $act;

$controller = new $controllerClassName;

$controller->$method();

echo 'END';
die;
